<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Prueba_Talycap_Ecopetrol.DTOs\Prueba_Talycap_Ecopetrol.DTOs.csproj" />
    <ProjectReference Include="..\Prueba_Talycap_Ecopetrol.Repositories\Prueba_Talycap_Ecopetrol.Repositories.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
